description = 'Transfer objects of the AMV Trafficsoft API'

dependencies {
    implementation "io.swagger:swagger-annotations:${swaggerVersion}"

    implementation "com.fasterxml.jackson.core:jackson-annotations:${jacksonVersion}"
    implementation "com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}"
}
