description = 'A Java client library for accessing the AMV Trafficsoft API'

dependencies {
    implementation project(':amv-trafficsoft-rest-model')

    implementation "io.github.openfeign:feign-core:${feignVersion}"
    implementation "io.github.openfeign:feign-okhttp:${feignVersion}"
    implementation "io.github.openfeign:feign-hystrix:${feignVersion}"
    implementation "io.github.openfeign:feign-slf4j:${feignVersion}"
    implementation "io.github.openfeign:feign-jackson:${feignVersion}"

    implementation "com.fasterxml.jackson.module:jackson-module-parameter-names:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jdk8:${jacksonVersion}"
    implementation "com.fasterxml.jackson.datatype:jackson-datatype-jsr310:${jacksonVersion}"

    testImplementation project(':amv-trafficsoft-rest-model-test')
    testImplementation 'com.marvinformatics.feign:feign-mock:0.7'

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    // legacy commons-lang (v2) used in tests for RandomStringUtils/RandomUtils
    testImplementation 'commons-lang:commons-lang:2.6'

}
