description = 'Autoconfigure for spring based applications accessing the AMV Trafficsoft API'

dependencies {
    implementation project(':amv-trafficsoft-rest-client')

    // Explicit Feign/Hystrix APIs used directly in this module
    implementation "io.github.openfeign:feign-core:${feignVersion}"
    implementation "io.github.openfeign:feign-hystrix:${feignVersion}"

    compileOnly "org.springframework.boot:spring-boot-configuration-processor:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-autoconfigure:${springBootVersion}"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation 'commons-lang:commons-lang:2.6'
}
